#!/usr/bin/env python3
"""Write M8RECT.INC for M8RECT.COM from an 86Box log made with MACH8_WLOG=1 while PC Paintbrush
drew one filled box on Windows/386 2.11 (8514.DRV), so the card and the 86Box model can be given the
same command stream and their pixels compared.

    python gen_m8rect.py <86box.log> <M8RECT.INC> <M8RECT.DAT>

The log's writes are split into groups that each end with a CMD (9AE8h) write. The window starts at
the box's fill (the last 40F3h with FRGD_COLOR 070Ch) and ends at the last C0D3h blit before the next
2037h line. Before it, every register's last value written ahead of the window is replayed (MULTIFUNC
indices kept apart) so the engine starts in the driver's state. The state goes to the .INC as
"dw port, value". The window, too large for a .COM, goes to the .DAT as the same word pairs ended by
a zero port, and M8RECT.COM reads it from disk.

pclog folds repeated lines, so "*** N repeats ***" is expanded: a row of solid pixels is a run of
identical PIX_TRANS words, and dropping them hands the card a short row.
"""
import struct
import sys

# pclog folds identical consecutive lines into "*** N repeats ***", which repeats the line before it.
w = []
last = None
for line in open(sys.argv[1], errors='replace'):
    if line.startswith('M8W '):
        a = line.split()
        last = (int(a[1], 16), int(a[2], 16))
        w.append(last)
    elif line.startswith('*** ') and line.rstrip().endswith(' repeats ***'):
        if last is not None:
            w.extend([last] * int(line.split()[1]))
    else:
        last = None

groups, cur = [], []
for x in w:
    cur.append(x)
    if x[0] == 0x9AE8:
        groups.append(cur)
        cur = []

fills = [i for i, g in enumerate(groups) if g[-1] == (0x9AE8, 0x40F3) and (0xA6E8, 0x070C) in g]
if not fills:
    raise SystemExit('no 40F3h fill with FRGD_COLOR 070Ch in the log')
first = fills[-1]
last = first
for i in range(first + 1, len(groups)):
    if groups[i][-1][1] == 0x2037:
        break
    if groups[i][-1][1] == 0xC0D3:
        last = i

# Drawing-engine state ahead of the window. Triggers and data ports are not state; the CRT, clock,
# display and shadow-set registers only change what the monitor shows, so the probe leaves them alone.
SKIP = {0x9AE8, 0xE2E8, 0xAEEE, 0xCAEE, 0x32EE, 0x42E8,
        0x02E8, 0x06E8, 0x0AE8, 0x0EE8, 0x12E8, 0x16E8, 0x1AE8, 0x1EE8, 0x22E8,
        0x46EE, 0x4AE8, 0x4AEE, 0x5AEE, 0x52EE, 0x56EE, 0x56EF}
state = {}
for g in groups[:first]:
    for p, v in g:
        if p in SKIP:
            continue
        key = (p, v >> 12) if p == 0xBEE8 else (p, None)
        state[key] = (p, v)

pre = [state[k] for k in sorted(state, key=lambda k: (k[0], -1 if k[1] is None else k[1]))]
body = [x for g in groups[first:last + 1] for x in g]
with open(sys.argv[2], 'w', newline='\r\n') as o:
    o.write('; generated by gen_m8rect.py: %d state writes, then groups %d-%d (%d writes)\n'
            % (len(pre), first, last, len(body)))
    o.write('state:\n')
    for p, v in pre:
        o.write('        dw      0%04Xh, 0%04Xh\n' % (p, v))
    o.write('        dw      0\n')
with open(sys.argv[3], 'wb') as o:
    for p, v in body:
        o.write(struct.pack('<HH', p, v))
    o.write(struct.pack('<HH', 0, 0))
print('%d state writes, groups %d-%d, %d writes, commands: %s' % (
    len(pre), first, last, len(body),
    ' '.join(sorted({'%04X' % g[-1][1] for g in groups[first:last + 1]}))))
