; A
        dw      05AEEh, 0001h
        dw      05AEEh, 0002h
        dw      05AEEh, 0000h
        dw      046EEh, 003Fh
        dw      05AEEh, 0001h
        dw      05AEEh, 0002h
        dw      05AEEh, 0000h
        dw      046EEh, 0000h
; B0
        dw      05AEEh, 0000h
        dw      002E8h, 0070h
        dw      05AEEh, 0000h
        dw      05AEEh, 0001h
        dw      05AEEh, 0002h
        dw      046EEh, 003Fh
        dw      05AEEh, 0000h
        dw      05AEEh, 0001h
        dw      05AEEh, 0002h
        dw      046EEh, 0000h
; B1
        dw      05AEEh, 0001h
        dw      002E8h, 0071h
        dw      05AEEh, 0000h
        dw      05AEEh, 0001h
        dw      05AEEh, 0002h
        dw      046EEh, 003Fh
        dw      05AEEh, 0000h
        dw      05AEEh, 0001h
        dw      05AEEh, 0002h
        dw      046EEh, 0000h
; B2
        dw      05AEEh, 0002h
        dw      002E8h, 0072h
        dw      05AEEh, 0000h
        dw      05AEEh, 0001h
        dw      05AEEh, 0002h
        dw      046EEh, 003Fh
        dw      05AEEh, 0000h
        dw      05AEEh, 0001h
        dw      05AEEh, 0002h
        dw      046EEh, 0000h
; C0
        dw      046EEh, 003Fh
        dw      05AEEh, 0000h
        dw      002E8h, 0080h
        dw      046EEh, 0000h
        dw      05AEEh, 0000h
        dw      05AEEh, 0001h
        dw      05AEEh, 0002h
        dw      046EEh, 003Fh
        dw      05AEEh, 0000h
        dw      05AEEh, 0001h
        dw      05AEEh, 0002h
; C1
        dw      046EEh, 003Fh
        dw      05AEEh, 0001h
        dw      002E8h, 0081h
        dw      046EEh, 0000h
        dw      05AEEh, 0000h
        dw      05AEEh, 0001h
        dw      05AEEh, 0002h
        dw      046EEh, 003Fh
        dw      05AEEh, 0000h
        dw      05AEEh, 0001h
        dw      05AEEh, 0002h
; C2
        dw      046EEh, 003Fh
        dw      05AEEh, 0002h
        dw      002E8h, 0082h
        dw      046EEh, 0000h
        dw      05AEEh, 0000h
        dw      05AEEh, 0001h
        dw      05AEEh, 0002h
        dw      046EEh, 003Fh
        dw      05AEEh, 0000h
        dw      05AEEh, 0001h
        dw      05AEEh, 0002h
        dw      0
